### PR TITLE
Use Sentinel with authentication

### LINKED ISSUE #594: Add support for sentinel authentication
In late 2018 sentinel got support for authentication. Currently predis does not support this due to d92f31dc66cd63c1f150891f2c40da75044df000. 

See: https://github.com/antirez/redis/commit/fa675256c127963c74ea68f8bab22ef105bada02

### PR DESCRIPTION
**Pull request by Leeloo5E**
closes #594

### CODE REVIEW

**Comment by tillkruss** [comment]
Please explain what issues is being resolved and how. Will this work with Sentinel without authentication?

**Comment by Leeloo5E** [comment]
Need to set authentification for Sentinels with different paaswords for redis itself and sentinels.

yes, it is working, if you use an empty password for sentinels and if a password for redis itself is set.

I only need to remove one line in file src/Connection/Aggregate/SentinelReplication.php

`
$parameters['password'] = null;
`

you have to configure an extra password for the sentinel as follow. The password for redis itself is set in options as before

```
   'sentinels' => [
    [
            'scheme' => 'tcp',
            'host' => '127.0.0.1',
            'port' => 26379,
            'password' => 'secret-sentinel-pw',
     ],
     ....
   ]
   'options' => [
        'replication' => 'sentinel',
        'service' => 'mymaster',
        'parameters' => [
            'password' => 'secret-redis-pw',
            'database' => 0,
      ],
   ]  
```

**Comment by Leeloo5E** [comment]
I removed the line now.

**Comment by tillkruss** [comment]
This seems like a risky merge. Please add test cases to `SentinelReplicationTest` for both password and no-password configs.

See https://github.com/predis/predis/commit/16957f3b39679b42b08ed2100debf4af89170fa4

**Comment by tillkruss** [comment]
Feel free to re-submit to the 2.0 `main` branch.

**Pull request closed without merging**
