### PR TITLE
[TESTING] Enable cluster testing on travis

### PR DESCRIPTION
**Pull request by tPl0ch**
This PR was extracted from https://github.com/nrk/predis/pull/300 and enables an automated `redis-cluster` setup within travis-ci using a custom `Makefile`

@nrk :)

### CODE REVIEW

**Comment by nrk** [comment]
Out of curiosity, why have a separate `phpunit.xml.cluster.travisci` file?

**Comment by tPl0ch** [comment]
Because the `redis-cluster` is only working with `REDIS_SERVER_VERSION >= 3.0`

**Comment by tPl0ch** [comment]
@nrk I am currently reviewing all my open PRs. Are you still interested in this? Otherwise I'd close it. Thanks!

**Comment by nrk** [comment]
@tPl0ch yes I'm definitely interested despite leaving this PR open for admittedly too much time. I still have some changes applied to your PR in a branch on my private repository (trying to have one single `phpunit.xml` and reuse the same ideas for redis-sentinel). If it's not a problem with you please leave it open, I'll see what I can do to have it merged.

**Pull request closed without merging**
