### PR TITLE
Unify code style

### PR DESCRIPTION
**Pull request by tillkruss**
@szepeviktor This repo could use some love.

### CODE REVIEW

**Comment by szepeviktor** [comment]
@tillkruss I have a ["default CI"](https://github.com/szepeviktor/debian-server-tools/blob/master/webserver/Continuous-integration-Continuous-delivery.yml) that has a cure for everything I've ever met.
But I'm afraid of rejection. It paralyzes me.

**Comment by tillkruss** [comment]
> @tillkruss I have a ["default CI"](https://github.com/szepeviktor/debian-server-tools/blob/master/webserver/Continuous-integration-Continuous-delivery.yml) that has a cure for everything I've ever met.

Let's do it! But call it lint.yml

**Comment by szepeviktor** [comment]
All right. Started working ... 🏃🏻‍♂️

This repository is a tech debt Tragedy!! 😿

**Comment by tillkruss** [comment]
It is, until you're done 😉

**Pull request merged**
