### PR TITLE
Replace goto operators

### PR DESCRIPTION
**Pull request by szepeviktor**
@tillkruss I'm no developer.
This was _donated_ to me.
Would you give it a go? 🟢

Please **DO NOT** merge this. This PR is only a question.

### CODE REVIEW

**Comment by tillkruss** [comment]
It would never throw the exception this way, which is needed.

**Comment by szepeviktor** [comment]
> It would never throw the exception this way, which is needed.

Is this a go or a no-go?

**Comment by tillkruss** [comment]
No-go, since it doesn't throw exceptions anymore.

**Comment by tillkruss** [comment]
I see your 2nd commit fixed the condition.

Why do you want to change the logic?

**Comment by szepeviktor** [comment]
> Why do you want to change the logic?

Because goto is the worst part of PHP.
There bad parts but goto it the worst. No software should have goto hidden inside.

**Comment by szepeviktor** [comment]
Fixing up to PHPStan level 2 is going on ...

**Comment by tillkruss** [comment]
> Because goto is the worst part of PHP. There bad parts but goto is the worst. No software should have goto hidden inside.

All operators are beautiful, we don't hate on `goto` around here.

**Comment by szepeviktor** [comment]
Emoootional overload!

**Pull request closed without merging**
