### PR TITLE
#923 Make MasterSlaveReplication iterable by extending AbstractConnection

### LINKED ISSUE #923: Error while iterating on `Predis\Client`: `Object of class Predis\Connection\Aggregate\MasterSlaveReplication could not be converted to string`
**Describe the bug**
I get a fatal error when iterating on a `Predis\Client` instance which connection is a `Predis\Connection\Aggregate\MasterSlaveReplication` instance.

**To Reproduce**
With `snc/redis-bundle 4.4.2` and `predis/predis 1.1.10`, `Symfony 5.4.16`, and `php 8.1.11` and the following config:

```yaml
snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn:
                - "%env(REDIS_URL)%?alias=master"
                - "%env(REDIS_URL_READ_ONLY)%"
            logging: '%kernel.debug%'
            options:
                replication: true
```

Then run:

```
$ bin/console redis:query flushall -vvv

In Client.php line 540:

  [Error]
  Object of class Predis\Connection\Aggregate\MasterSlaveReplication could not be converted to string


Exception trace:
  at /srv/app/vendor/predis/predis/src/Client.php:540
 Predis\Client->getIterator() at /srv/app/vendor/snc/redis-bundle/src/Command/RedisQueryCommand.php:86
 Snc\RedisBundle\Command\RedisQueryCommand->execute() at /srv/app/vendor/symfony/console/Command/Command.php:312
 Symfony\Component\Console\Command\Command->run() at /srv/app/vendor/symfony/console/Application.php:1038
 Symfony\Component\Console\Application->doRunCommand() at /srv/app/vendor/symfony/framework-bundle/Console/Application.php:96
 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at /srv/app/vendor/symfony/console/Application.php:312
 Symfony\Component\Console\Application->doRun() at /srv/app/vendor/symfony/framework-bundle/Console/Application.php:82
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /srv/app/vendor/symfony/console/Application.php:168
 Symfony\Component\Console\Application->run() at /srv/app/bin/console:43

redis:query [--client CLIENT] [--] <query>...
```

**Expected behavior**
It should output:

```
DEBUG     [snc_redis] Executing command "FLUSHALL"
^ Predis\Response\Status^ {#389
  -payload: "OK"
}
```

**Versions (please complete the following information):**
 - Predis: 1.1.10
 - snc/redis-bundle 4.4.2
 - Symfony 5.4.16
 - PHP 8.1.11
 - Redis Server: bitnami/redis:6.2.6

**Code sample**
The code that tries to iterate on the client is [here](https://github.com/snc/SncRedisBundle/blob/master/src/Command/RedisQueryCommand.php#L86).

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by Gregoire-M**
Fixes #923

### CODE REVIEW

**Comment by tillkruss** [comment]
Looks like Travis CI isn't running anymore for `v1.1`, I'll be honest, I can't be arsed to get CI working again for the branch.

So `v1.1.10` was likely the last release. If you can show me a fully passing test suite, I can merge it if you insist.

**Comment by Gregoire-M** [comment]
image

Well, I have a bunch of errors, but I have them when I revert my diff too (on PHP 8.2.1, with Redis 7.0.7).

**Comment by tillkruss** [comment]
>Builds have been temporarily disabled for public repositories due to a negative credit balance. Please go to the Plan page to replenish your credit balance or alter your Consume paid credits for OSS setting.

Looks like we need to pay now, which I won't.

I'd strongly suggest using Predis v2, or patch v1.1 yourself. We can try running this again in February, since I made some changes bb8cce7.

**Comment by Gregoire-M** [comment]
I understand.

I'll try using v2?

**Pull request closed without merging**
