### PR TITLE
Added ZPOPMIN and ZPOPMAX

### PR DESCRIPTION
**Pull request by lulco**
Resolves https://github.com/predis/predis/issues/755

### CODE REVIEW

**Comment by tillkruss** [comment]
What version where these added in?

**Comment by lulco** [comment]
5.0.0, that's why I didn’t add it to 1.1 branch
In main I didn’t find any map command to version. Can you navigate me how to make tests pass?

**Comment by tillkruss** [comment]
I think maybe we should push v2.0 out the door with proper support for all the new Redis versions.

**Comment by lulco** [comment]
Ok, I don’t get it :) what does it mean for me and my pull request? :)

**Comment by tillkruss** [comment]
Just that it might take a little bit until we release the first v2 version.

PR looks great.

**Comment by tillkruss** [comment]
@lulco Do you have any input to the test failures on Redis 3 and 4? Should we simply skip the tests?

**Comment by lulco** [comment]
I was thinking about skipping for redis < 5.0.0, just don’t know how to do it? Some env variable? Or connect to redis run info command and get version from it?

**Comment by lulco** [comment]
patch added and main branch merged into PR, please approve workflow to run tests

**Comment by zaherg** [comment]
@tillkruss can you approve it?

**Pull request merged**
