### PR TITLE
See PHPStan level 2 problems in action

### PR DESCRIPTION
**Pull request by szepeviktor**
Just checking output 🧪

### CODE REVIEW

**Comment by szepeviktor** [comment]
@tillkruss Could you help me resolving exception to string casting?
https://github.com/predis/predis/blob/c201af5ad308dd419ddc2494bb7fecaf8a8cd570/src/Client.php#L275-L293

**Comment by tillkruss** [comment]
> @tillkruss Could you help me resolving `ResponseInterface` to string casting?

Maybe ignore it for now in the neon file, and we tackle the tricky ones later one by one.

**Comment by szepeviktor** [comment]
> and we tackle the tricky ones later one by one

:) that _later_ could be now, and this is the first one :)

**Comment by szepeviktor** [comment]
👆🏻 What a lovely Coveralls comment.

On their Settings page you can switch to "small comment". (that is a viktor invention 🤫 )

**Comment by tillkruss** [comment]
This is what it's set to currently.

Screenshot 2023-01-21 at 1 55 31 PM

**Pull request closed without merging**
