### PR TITLE
Add partial support for Stream commands

### PR DESCRIPTION
**Pull request by TobiasBengtsson**
Adds support for the following commands not related to groups/consumers: XADD, XDEL, XLEN, XRANGE, XREVRANGE, XTRIM.

### CODE REVIEW

**Comment by tillkruss** [comment]
Nice, can you fix the tests?

**Comment by TobiasBengtsson** [comment]
Updated, apart from a couple of typos it was related to `stream-node-max-entries` config that we need to control for deterministic tests. I moved it from `setUp` and `tearDown` to the individual tests to just run them on supported versions.

The potential problem here is if you have one failure the config will never be reset for the test run (even worse locally: never). I could add try-catch blocks around the test, but if you can think of any better way to handle it I'm all ears

**Comment by tillkruss** [comment]
I've relaxed the permissions, so workflows always run 🥲

**Comment by tillkruss** [comment]
Thanks for the test fixes, I assume a re-run would resolve this. If they are too unable we can tweak them later. Thanks for the contribution!

**Pull request merged**
