### PR TITLE
Upgrade static analysis to PHPStan level 2

### PR DESCRIPTION
**Pull request by szepeviktor**
From #1041 and some type fixes in tests.

### CODE REVIEW

**Comment by szepeviktor** [comment]
**Now* the comment is really _small_.

**Comment by szepeviktor** [comment]
PHP-CS-Fixer is not the best tool in the world ...
PHPCS is old an rotten but able to output GHA annotations (and I'm involved in it)
https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/issues/5482

**Comment by szepeviktor** [comment]
kép

That leading slash was the problem.

**Comment by szepeviktor** [comment]
My fork's source files are available on Coveralls.
https://coveralls.io/builds/56165207/source?filename=src%2FCommand%2FArgument%2FGeospatial%2FFromMember.php
Maybe some kind of permission issue?
I do not know.

**Comment by szepeviktor** [comment]
Once I log in to Coveralls, source files appear 🥂 https://coveralls.io/builds/56165441/source?filename=src%2FCluster%2FPredisStrategy.php

**Review by tillkruss — APPROVED** [review]

**Pull request merged**
