### PR TITLE
add SSL support

### PR DESCRIPTION
**Pull request by oranagra**
Adding SSL support. Tested against stunnel on the server side.

### CODE REVIEW

**Comment by tomcastleman** [comment]
Hi @oranagra 

I found this PR whilst investigating the Redis Cloud service. Encryption is a key requirement when using third party services over untrusted networks. On PaaS providers like Heroku there is no option to use stunnel so the feature implemented by this PR is really important.

Have you thought about pursuing this PR along the lines @nrk suggested?

Thanks

**Comment by oranagra** [comment]
Hi @tomcastleman 
I'm currently busy with other projects, if you have the time, maybe do it yourself.
Let me know if my assistance is needed to push it into the existing PR, or create a new one.
Thanks.

**Comment by nrk** [comment]
@oranagra, @tomcastleman support for SSL will be added to Predis v1.1 but will be limited to `Predis\Connection\StreamConnection` (the default connection backend) at least until I find a solution to make it work for `Predis\Connection\PhpiredisStreamConnection` too (I have an idea, but also have other priorities for the library right now). I will push the code on GitHub in a couple of days, but things seems to be working fine already. The accepted URI schemes will be `tls` and `rediss`.

**Comment by oranagra** [comment]
Hi,
I think that supporting SSL with the default connection class may be enough.
I don't think you can support SSL in PhpiredisStreamConnection unless support for SSL is added for hiredis first.
Thanks.

**Comment by nrk** [comment]
@oranagra the `Predis\Connection\PhpiredisStreamConnection` only uses the RESP stream parser provided by hiredis, network-related stuff still happens in userland PHP code :-)

**Comment by itamarhaber** [comment]
@nrk please also take into consideration the Reids URI discussion that's taking place at https://groups.google.com/forum/#!topic/redis-db/elyRy9KDRtI

**Comment by nrk** [comment]
@itamarhaber both the `redis` and `rediss` schemes will be supported by Predis (well actually `redis` is already in the `v1.0` branch, will be available starting with v1.0.2) following the rules described on the respective provisional URI scheme registration documents. as opposed with `tcp` and `tls` which will stick with the current Predis-specific way of specifying both password and database.

**Comment by nrk** [comment]
Implemented in commit ebb7237 available on the `master` branch (targeting the next minor release of Predis, v1.1).

**Pull request closed without merging**
