### PR TITLE
Update .gitattributes

### PR DESCRIPTION
**Pull request by angeljqv**
Make the vendor 56kb smaller,
is it possible or is there any reason not to do it?

### CODE REVIEW

**Comment by tillkruss** [comment]
We can certainly do that.

**Comment by mfn** [comment]
👎🏼 on removing CHANGELOG from the installed vendor files, it's very useful to be able to quickly check the latest changes.

**Comment by tillkruss** [comment]
@mfn: If you want to open a PR to split up the changeling like Laravel does, that's cool.

The `v1.1` branch should only contains `v1.1.x` release notes.

**Comment by angeljqv** [comment]
split is a great option too 👍

**Pull request merged**
