### PR TITLE
Added 3.0 changelog and documentation update

### PR DESCRIPTION
**Pull request by vladvildanov**

### CODE REVIEW

**Comment by vladvildanov** [comment]
@uglide Needs your review on it

**Comment by tillkruss** [comment]
What commits does this cover?

**Comment by vladvildanov** [comment]
@tillkruss I linked GA issues in README, so it covers exactly this PR's

**Comment by chayim** [comment]
@vladvildanov There's no reason for the CI failure - purely from the READMEs. Can you please have a look.

**Review by chayim — COMMENTED** [review]
Approving the content. However, I'd still like to see CI investigated. That can clearly be a separate PR to keep it surgical. There's no (logical) reason these README changes should have impacted.

**Comment by vladvildanov** [comment]
@chayim It's failing because of `redis-stack-server:latest` image was updated. Already been fixed within this PR

https://github.com/predis/predis/pull/1348

**Pull request merged**
