### PR TITLE
Drop HHVM

### LINKED ISSUE #618: Drop HHVM support
Like most PHP packages, let's drop HHVM support in v2.0. v1.1 will continue to support it, but will only receive bug fixes.

### PR DESCRIPTION
**Pull request by tillkruss**
Resolves #618.

### CODE REVIEW

**Comment by tillkruss** [comment]
https://github.com/predishq/predis/blob/main/src/Configuration/ProfileOption.php#L32-L42

@nrk: Can we drop, too?

**Comment by nrk** [comment]
Dropping support for HHVM means that we can remove any hack related to it from the codebase.

On a related note, honestly I'd slow things down a bit for now with merging stuff that modifies too much of the source code on `main` as it might end up giving us some headaches later when porting the changes back from `master-stale`, as I'm pretty sure most stuff from there is still valid and could even be re-applied as-is, with just some squashing and a few clean-ups (see #624).

Just give me a few days at least to investigate 😃

**Comment by tillkruss** [comment]
@nrk sure, no problem!

**Comment by nrk** [comment]
I didn't even notice but I removed all of the HHVM-related hacks in #654 which is now merged into `main`, so we can close this.

**Pull request closed without merging**
