### PR TITLE
Check if socket is resource before reading

### PR DESCRIPTION
**Pull request by streamingsystems**
Per your request, here is the PR for checking if the socket is a resource prior to reading.

### CODE REVIEW

**Comment by tillkruss** [comment]
This can't hurt and won't impact performance that much.

**Comment by streamingsystems** [comment]
This is a dumb question but I already have 2.02 in my composer.lock and I can't seem to get this file change down. Do you need to bump to 2.03 so I will get the change?

**Comment by mfn** [comment]
> Do you need to bump to 2.03 so I will get the change?

Yes, a new release needs to be done for it to appear.

Note: you can try out releases before they are done by [using `2.0-dev` as version](https://github.com/predis/predis/blob/42c33a406f1fc8f63dc91a2cc32a5fd832659ec6/composer.json#L47) (at your own risk)

**Comment by tillkruss** [comment]
Wouldn't it be `dev-main`?

**Comment by streamingsystems** [comment]
Thanks. Do you know when your next release is planned? We would like to get this fix into production as soon as we can. We have other packages that reply on predis that we moved to “^2.0” in composer from 1.1.

From: Markus Podar ***@***.***>
Date: Monday, September 19, 2022 at 1:48 AM
To: predis/predis ***@***.***>
Cc: streamingsystems ***@***.***>, Author ***@***.***>
Subject: Re: [predis/predis] Check if socket is resource before reading (PR #802)

Do you need to bump to 2.03 so I will get the change?

Yes, a new release needs to be done for it to appear.

Note: you can try out releases before they are done by using 2.0-dev as version<https://github.com/predis/predis/blob/42c33a406f1fc8f63dc91a2cc32a5fd832659ec6/composer.json#L47> (at your own risk)

**Comment by tillkruss** [comment]
@streamingsystems: Tagged v2.0.3 just now.

**Pull request merged**
